# Site settings
title: Basetelecom
subtitle: by SOFTPOINTZONE
email: contato@basetelecom.com.br
description: Agente autorizado Claro Empresas com foco em identificar as <br /> necessidades do cliente provendo atendimento personalizado no pré e pós-venda.
baseurl: "/softpointzone" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Avenida Horário Raccanello
city: 626 sala
state: 02 Novo Centro
zip_code:
country: Maringá(PR)
phone: 0800 014 1212

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown

sass:
  style: compressed
